"""LLM judge client for evaluating free-form text outputs."""

import logging
import re

from gitbench.harness.model import ModelInterface
from gitbench.harness.types import ModelMessage

logger = logging.getLogger(__name__)

JUDGE_COMMIT_MESSAGE_PROMPT = """You are evaluating the quality of a commit message for a git diff.

First, review the original prompt given to the model:

<original_prompt>
{prompt}
</original_prompt>

Score the commit message on a scale from 0.0 to 1.0 based on:
- Does it accurately describe the changes in the diff?
- Is it concise and well-structured?
- Does it follow the instructions in the original prompt (length limits, format, etc.)?
- Does it contain ONLY the commit message (no reasoning, no extra commentary)?
- Does it follow conventional commit message format?
- Does it capture the intent and scope of the change?

Penalize heavily if the response includes reasoning, explanations, or anything
other than the requested commit message.

Return ONLY a number between 0.0 and 1.0. Do not include any explanation.

Git diff:
{diff}

Commit message:
{message}

Score:"""


class JudgeClient:
    """Wraps multiple model clients to evaluate free-form text outputs.

    The judge calls every model client in the profile and averages their
    scores. Each client is configured with ``retry_count=5`` and handles
    rate limiting via ``Retry-After`` headers internally.

    Only when *all* clients fail does the judge raise an error — which the
    Scorer catches and falls back to SequenceMatcher.
    """

    def __init__(self, model_clients: list[ModelInterface]) -> None:
        """Initialise the judge client.

        Args:
            model_clients: One or more model adapters. Every client is
                called and their scores are averaged. Each should be
                configured with ``retry_count=5``.
        """
        if not model_clients:
            raise ValueError("JudgeClient requires at least one model client")
        self._model_clients = model_clients

    def evaluate_commit_message(self, diff: str, message: str, prompt: str = "") -> float:
        """Evaluate a commit message against a git diff and original prompt.

        Calls every model client, collects their scores, and returns the
        average. Each client has its own internal retry loop with
        rate-limit backoff — the judge does not add an extra retry layer.

        Args:
            diff: The git diff to evaluate against.
            message: The commit message generated by the model under test.
            prompt: The original prompt given to the model under test, so
                the judge can evaluate instruction-following.

        Returns:
            A float between 0.0 and 1.0 — the average of all judge scores.

        Raises:
            ValueError: If all judge models fail or all responses cannot
                be parsed as numbers.
        """
        judge_prompt = JUDGE_COMMIT_MESSAGE_PROMPT.format(
            diff=diff, message=message, prompt=prompt
        )
        messages = [ModelMessage(role="user", content=judge_prompt)]

        scores: list[float] = []
        errors: list[str] = []

        for i, client in enumerate(self._model_clients):
            model_name = getattr(client, "model", f"client-{i}")
            try:
                logger.debug(
                    "Judge calling model %d/%d (%s)",
                    i + 1,
                    len(self._model_clients),
                    model_name,
                )
                response = client.generate(messages)
                text = self._extract_text(response)
                score = self._parse_score(text)
                scores.append(score)
                logger.debug("Judge model '%s' scored %.2f", model_name, score)
            except Exception as exc:
                logger.warning(
                    "Judge model '%s' failed (%d/%d): %s",
                    model_name,
                    i + 1,
                    len(self._model_clients),
                    exc,
                )
                errors.append(f"{model_name}: {exc}")

        if not scores:
            raise ValueError(
                f"All {len(self._model_clients)} judge model(s) failed. "
                f"Errors: {'; '.join(errors)}"
            )

        average = sum(scores) / len(scores)
        logger.info(
            "Judge ensemble: %d/%d models returned scores, average=%.3f",
            len(scores),
            len(self._model_clients),
            average,
        )
        return round(average, 4)

    def _extract_text(self, response) -> str:
        """Extract text from a model response (dict or string)."""
        if isinstance(response, dict):
            return response.get("text", response.get("content", ""))
        return str(response)

    def _parse_score(self, text: str) -> float:
        """Parse a numeric score from the judge model response.

        Args:
            text: The raw response text from the judge model.

        Returns:
            A float between 0.0 and 1.0.

        Raises:
            ValueError: If no numeric score can be extracted.
        """
        # Try to find a float number in the response (optionally signed)
        match = re.search(r"(-?\d+(?:\.\d+)?)", text)
        if not match:
            raise ValueError(
                f"Judge response could not be parsed as a number: {text!r}"
            )

        score = float(match.group(1))

        # Clamp to valid range
        if score < 0.0:
            score = 0.0
        elif score > 1.0:
            score = 1.0

        return score
