"""HTML report renderer for GitBench results."""

import json
import logging
import sqlite3
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from gitbench.harness.model import parse_model_name

logger = logging.getLogger(__name__)

WEB_DIR = Path(__file__).resolve().parent.parent / "web"
REPORT_DB_PATH = WEB_DIR / "data" / "gitbench.db"
REPORT_SCHEMA_PATH = WEB_DIR / "data" / "schema.sql"


def load_runs_from_dir(directory: str) -> list[dict]:
    """Load all run envelope JSON files from a directory.

    Args:
        directory: Path to directory containing JSON run files.

    Returns:
        List of run envelope dicts, sorted by suite version then timestamp.
    """
    dir_path = Path(directory)
    if not dir_path.exists():
        raise FileNotFoundError(f"Directory not found: {directory}")

    runs = []
    for f in sorted(dir_path.glob("*.json")):
        try:
            data = json.loads(f.read_text())
            if "version" in data and "results" in data:
                runs.append(data)
        except (json.JSONDecodeError, KeyError):
            continue

    runs.sort(key=_run_sort_key)
    return runs


def load_runs_from_jsonl(path: str) -> list[dict]:
    """Load run envelopes from a JSONL file.

    Args:
        path: Path to JSONL file.

    Returns:
        List of run envelope dicts, sorted by suite version then timestamp.
    """
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    runs = []
    for line in file_path.read_text().strip().split("\n"):
        if not line.strip():
            continue
        try:
            data = json.loads(line)
            if "version" in data and "results" in data:
                runs.append(data)
        except (json.JSONDecodeError, KeyError):
            continue

    runs.sort(key=_run_sort_key)
    return runs


def _is_raw_run_envelope(data: dict) -> bool:
    return "version" in data and "results" in data and "model" in data


def _is_aggregate_report_json(data: dict) -> bool:
    """Return True for generated report JSON, not raw/combined run output."""
    return all(key in data for key in ("models", "model_summaries", "matrix", "fixtures"))


def load_aggregate_report(path: str) -> dict[str, Any] | None:
    """Load an already-aggregated report JSON file, if the file is one.

    Aggregate report files are generated by older ``gitbench run --output-mode
    both`` behavior and by ``gitbench report``. They are not raw run envelopes,
    but they still contain complete report data and should be usable as report
    input.
    """
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    data = json.loads(file_path.read_text())
    if isinstance(data, dict) and _is_aggregate_report_json(data):
        return data
    return None


def _empty_report_data() -> dict[str, Any]:
    return {
        "models": [],
        "benchmarks": [],
        "model_summaries": {},
        "model_runtimes": {},
        "matrix": {},
        "fixtures": {},
        "fixture_index": {},
        "runs_meta": [],
        "base_model_groups": [],
        "campaigns": [],
    }


def merge_aggregate_reports(reports: list[dict[str, Any]]) -> dict[str, Any]:
    """Merge aggregate report JSON payloads into one report data object."""
    merged = _empty_report_data()
    models_by_name: dict[str, dict] = {}
    groups: dict[tuple[str, str], dict] = {}
    runs_seen: set[tuple[str, str, str, str]] = set()

    for report in reports:
        for model in report.get("models", []):
            name = model.get("name")
            if name:
                models_by_name[name] = model

        merged["benchmarks"] = sorted(
            set(merged["benchmarks"]) | set(report.get("benchmarks", []))
        )

        for key in (
            "model_summaries",
            "model_runtimes",
            "matrix",
            "fixtures",
            "fixture_index",
        ):
            merged[key].update(report.get(key, {}))

        if "model_token_summaries" in report:
            merged.setdefault("model_token_summaries", {}).update(
                report.get("model_token_summaries", {})
            )

        for run in report.get("runs_meta", []):
            run_key = (
                run.get("benchmark_suite_version", ""),
                run.get("timestamp", ""),
                run.get("model", ""),
                run.get("output_mode", "text"),
            )
            if run_key in runs_seen:
                continue
            runs_seen.add(run_key)
            merged["runs_meta"].append(run)

        for group in report.get("base_model_groups", []):
            provider = group.get("provider", "")
            base_model = group.get("baseModel", "")
            if not provider or not base_model:
                continue
            group_key = (provider, base_model)
            existing = groups.setdefault(
                group_key,
                {"provider": provider, "baseModel": base_model, "levels": []},
            )
            levels_by_model = {
                level.get("modelName"): level
                for level in existing["levels"]
                if level.get("modelName")
            }
            for level in group.get("levels", []):
                model_name = level.get("modelName")
                if model_name:
                    levels_by_model[model_name] = level
            existing["levels"] = list(levels_by_model.values())

    merged["models"] = sorted(models_by_name.values(), key=lambda m: m.get("name", ""))
    merged["runs_meta"].sort(key=lambda r: (r.get("benchmark_suite_version", ""), r.get("timestamp", "")))
    merged["base_model_groups"] = sorted(
        groups.values(),
        key=lambda g: (g.get("provider", ""), g.get("baseModel", "")),
    )
    campaigns_by_id: dict[str, dict] = {}
    for report in reports:
        for campaign in report.get("campaigns", []):
            campaign_id = campaign.get("campaign_id")
            if campaign_id:
                campaigns_by_id[campaign_id] = campaign
    merged["campaigns"] = sorted(
        campaigns_by_id.values(),
        key=lambda c: c.get("created_at", ""),
    )
    return merged


def load_campaign_reports_from_dir(directory: str) -> list[dict[str, Any]]:
    """Load campaign artifacts from directories containing ``campaign.json``."""
    from gitbench.export import build_campaign_report
    from gitbench.harness.campaign_store import CampaignStore

    root = Path(directory)
    if not root.exists():
        return []

    reports: list[dict[str, Any]] = []
    manifest_paths = sorted(root.glob("campaign.json"))
    if root.is_dir():
        manifest_paths.extend(sorted(root.glob("*/campaign.json")))

    for manifest_path in manifest_paths:
        campaign_id = manifest_path.parent.name
        store = CampaignStore(campaign_id, base_dir=manifest_path.parent.parent)
        campaign = store.load_manifest()
        if campaign is None:
            continue
        campaign.raw_attempts = store.load_all_attempts()
        report = build_campaign_report(campaign)
        reports.append(campaign_report_to_aggregate_data(report.to_dict()))
    return reports


def campaign_report_to_aggregate_data(report: dict[str, Any]) -> dict[str, Any]:
    """Convert a campaign report into aggregate report-data shape."""
    data = _empty_report_data()
    campaign = dict(report.get("campaign") or {})
    config = campaign.get("config") or {}
    campaign["benchmark_ids"] = config.get("benchmark_ids", [])
    campaign["model_ids"] = config.get("model_ids", [])
    campaign["output_modes"] = config.get("output_modes", [])
    campaign["planned_trial_count"] = config.get("planned_trial_count", 1)
    campaign["model_summaries"] = report.get("model_summaries", [])
    campaign["benchmark_summaries"] = report.get("benchmark_summaries", [])
    campaign["resource_summaries"] = report.get("resource_summaries", [])
    data["campaigns"] = [campaign]
    data["benchmarks"] = sorted(set(config.get("benchmark_ids", [])))

    fixture_index: dict[str, dict] = {}
    for attempt in campaign.get("raw_attempts", []):
        identity = attempt.get("identity", {})
        benchmark = identity.get("benchmark") or (
            identity.get("fixture_id", "").split("/", 1)[0]
            if "/" in identity.get("fixture_id", "")
            else ""
        )
        fixture_id = identity.get("fixture_id", "")
        if benchmark and fixture_id:
            fixture_index[f"{benchmark}/{fixture_id}"] = {
                "id": fixture_id,
                "benchmark": benchmark,
                "prompt": "",
                "expected": "",
                "description": "",
                "setup": [],
                "purpose": "",
                "difficulty": "",
                "tags": [],
            }
    for qualified_fixture in config.get("fixture_ids", []):
        if "/" not in qualified_fixture:
            continue
        benchmark, fixture_id = qualified_fixture.split("/", 1)
        fixture_index.setdefault(
            f"{benchmark}/{fixture_id}",
            {
                "id": fixture_id,
                "benchmark": benchmark,
                "prompt": "",
                "expected": "",
                "description": "",
                "setup": [],
                "purpose": "",
                "difficulty": "",
                "tags": [],
            },
        )
    _supplement_fixture_index_from_yaml(fixture_index)
    data["fixture_index"] = fixture_index
    return data


def load_runs_from_combined(path: str) -> list[dict]:
    """Load run envelopes from a combined results JSON file.

    The combined format (produced by default from ``gitbench run -a``)
    nests results under profiles → models.  This function extracts each
    model's results into individual run envelope dicts.

    Args:
        path: Path to the combined results JSON file.

    Returns:
        List of run envelope dicts, sorted by suite version then timestamp.
    """
    file_path = Path(path)
    if not file_path.exists():
        raise FileNotFoundError(f"File not found: {path}")

    data = json.loads(file_path.read_text())
    runs: list[dict] = []

    if not isinstance(data, dict):
        return runs

    if _is_aggregate_report_json(data):
        return runs

    if _is_raw_run_envelope(data):
        return [data]

    suite_version = data.get("benchmark_suite_version", "")
    # Try to get timestamp from the file's parent directory name (ISO format)
    timestamp = ""
    parent_name = file_path.parent.name
    if parent_name and parent_name[0].isdigit():
        # Directory name like 20260511T220621Z → convert to ISO
        try:
            from datetime import datetime
            dt = datetime.strptime(parent_name, "%Y%m%dT%H%M%SZ")
            timestamp = dt.isoformat() + "Z"
        except ValueError:
            pass

    # Format 1: multi-profile ("profiles" key)
    for profile_entry in data.get("profiles", []):
        profile_name = profile_entry.get("profile", "")
        for model_entry in profile_entry.get("models", []):
            model_name = model_entry.get("model", "")
            model_results = model_entry.get("results", [])
            runs.append({
                "version": "0.1.0",
                "model": model_name,
                "profile": profile_name,
                "benchmark_suite_version": suite_version,
                "timestamp": timestamp,
                "output_mode": model_entry.get("output_mode", "text"),
                "results": model_results,
            })

    # Format 2: single-profile multi-model ("models" key but no "profiles")
    if not runs and "models" in data and "profiles" not in data:
        for model_entry in data["models"]:
            model_name = model_entry.get("model", "")
            model_results = model_entry.get("results", [])
            runs.append({
                "version": "0.1.0",
                "model": model_name,
                "profile": data.get("profile", ""),
                "benchmark_suite_version": suite_version,
                "timestamp": timestamp,
                "output_mode": model_entry.get("output_mode", "text"),
                "results": model_results,
            })

    # Format 3: flat per-benchmark result
    if not runs and "benchmark" in data and "scores" in data:
        runs.append({
            "version": "0.1.0",
            "model": data.get("model", "unknown"),
            "profile": data.get("profile", ""),
            "benchmark_suite_version": suite_version,
            "timestamp": timestamp,
            "output_mode": data.get("output_mode", "text"),
            "results": [data],
        })

    runs.sort(key=_run_sort_key)
    return runs


def _default_output_timestamp() -> str:
    """Return the timestamp fragment used for default run output paths."""
    from datetime import datetime, timezone
    return datetime.now(timezone.utc).strftime("%Y%m%dT%H%M%SZ")


def _version_sort_key(version: str) -> tuple[int, ...]:
    """Return a numeric-ish sort key for dotted version strings."""
    parts = []
    for part in version.split("."):
        try:
            parts.append(int(part))
        except ValueError:
            parts.append(0)
    return tuple(parts)


def _run_sort_key(run: dict) -> tuple[tuple[int, ...], str]:
    """Sort runs by benchmark suite version first, then timestamp."""
    return (
        _version_sort_key(str(run.get("benchmark_suite_version", ""))),
        run.get("timestamp", ""),
    )


def _parse_model_parts(model_name: str) -> tuple[str, str, str | None]:
    """Parse a model name into provider, base model, and reasoning level.

    Handles ``provider/base:level`` format (try ``:``, fallback ``#``,
    handle no level).

    Returns:
        Tuple of ``(provider, base_model, reasoning_level)``.
    """
    if "/" not in model_name:
        return (model_name, model_name, None)

    provider, rest = model_name.split("/", 1)

    # Try ``:`` first (OpenRouter format), fall back to ``#``
    if ":" in rest:
        base_model, level = rest.split(":", 1)
    elif "#" in rest:
        base_model, level = rest.split("#", 1)
    else:
        return (provider, rest, None)

    return (provider, base_model, level if level else None)


def aggregate_runs(runs: list[dict]) -> dict[str, Any]:
    """Aggregate multiple runs into a structured summary for rendering.

    Runs are keyed by ``model + output_mode`` so that text and json_schema
    runs for the same model remain separate variants.

    Args:
        runs: List of run envelope dicts.

    Returns:
        Dict with models, benchmarks, summaries, matrix, fixtures, etc.
    """
    models_set: set[str] = set()
    benchmarks_set: set[str] = set()
    model_data: dict[str, dict] = {}

    for run in runs:
        model = run["model"]
        output_mode = run.get("output_mode", "text")  # default missing to text

        # Composite key: model + output_mode to keep variants separate
        model_key = f"{model}__{output_mode}" if output_mode != "text" else model

        models_set.add(model_key)

        if model_key not in model_data:
            model_data[model_key] = {
                "total_runs": 0,
                "total_fixtures": 0,
                "total_passed": 0,
                "benchmarks": {},
                "api_durations_ms": [],
                "_model": model,
                "_output_mode": output_mode,
            }

        model_data[model_key]["total_runs"] += 1

        for result in run.get("results", []):
            if "error" in result and "benchmark" not in result:
                continue

            bench = result.get("benchmark", "unknown")
            benchmarks_set.add(bench)

            if bench not in model_data[model_key]["benchmarks"]:
                model_data[model_key]["benchmarks"][bench] = {
                    "total": 0,
                    "passed": 0,
                    "scores": [],
                    "fixtures": [],
                }

            bd = model_data[model_key]["benchmarks"][bench]
            bd["total"] += result.get("total", 0)
            bd["passed"] += result.get("passed", 0)

            for score in result.get("scores", []):
                structured_error = score.get("structured_error")
                bd["scores"].append(score.get("similarity", 0))
                bd["fixtures"].append({
                    "fixture_id": score.get("fixture_id", "?"),
                    "passed": score.get("passed", False),
                    "similarity": score.get("similarity", 0),
                    "error": score.get("error"),
                    "model_output": score.get("model_output", ""),
                    "reasoning_level": score.get("reasoning_level"),
                    "input_tokens": score.get("input_tokens"),
                    "output_tokens": score.get("output_tokens"),
                    "total_tokens": score.get("total_tokens"),
                    "reasoning_tokens": score.get("reasoning_tokens"),
                    "cost_usd": score.get("cost_usd"),
                    "purpose": score.get("purpose"),
                    "difficulty": score.get("difficulty"),
                    "tags": score.get("tags"),
                    "duration_ms": score.get("duration_ms"),
                    "api_duration_ms": score.get("api_duration_ms"),
                    "output_mode": score.get("output_mode", output_mode),
                    "parsed_payload": (
                        None if structured_error else score.get("parsed_payload")
                    ),
                    "raw_structured_output": score.get("raw_structured_output"),
                    "structured_error": structured_error,
                    "safety_review": score.get("safety_review"),
                })
                # Report runtime is successful API call latency, not fixture wall time.
                if score.get("api_duration_ms") is not None:
                    model_data[model_key]["api_durations_ms"].append(
                        score["api_duration_ms"]
                    )

    # Build summaries and matrix
    model_summaries = {}
    matrix = {}
    fixtures = {}

    for model, data in model_data.items():
        model_summaries[model] = {
            "total_runs": data["total_runs"],
            "total_fixtures": data["total_fixtures"],
            "total_passed": data["total_passed"],
            "pass_at_k": round(
                data["total_passed"] / data["total_fixtures"], 4
            ) if data["total_fixtures"] > 0 else 0.0,
            "total_cost_usd": None,
            "avg_cost_usd": None,
        }

        matrix[model] = {}
        fixtures[model] = {}

        model_cost_sum = 0.0
        model_cost_count = 0

        for bench, bd in data["benchmarks"].items():
            avg_sim = round(sum(bd["scores"]) / len(bd["scores"]), 4) if bd["scores"] else 0.0
            matrix[model][bench] = {
                "pass_at_k": round(bd["passed"] / bd["total"], 4) if bd["total"] > 0 else 0.0,
                "total": bd["total"],
                "passed": bd["passed"],
                "avg_similarity": avg_sim,
            }
            fixtures[model][bench] = bd["fixtures"]

            # Collect cost data for this model
            for fx in bd["fixtures"]:
                if fx.get("cost_usd") is not None:
                    model_cost_sum += fx["cost_usd"]
                    model_cost_count += 1

            # Roll up to model summary
            model_summaries[model]["total_fixtures"] += bd["total"]
            model_summaries[model]["total_passed"] += bd["passed"]

        # Recompute pass_at_k after rollup
        sf = model_summaries[model]
        sf["pass_at_k"] = round(
            sf["total_passed"] / sf["total_fixtures"], 4
        ) if sf["total_fixtures"] > 0 else 0.0

        if model_cost_count > 0:
            sf["total_cost_usd"] = round(model_cost_sum, 10)
            sf["avg_cost_usd"] = round(model_cost_sum / model_cost_count, 10)

    # Build model runtime summaries
    model_runtimes: dict[str, dict] = {}
    for model, data in model_data.items():
        durations = data.get("api_durations_ms", [])
        if durations:
            model_runtimes[model] = {
                "total_ms": round(sum(durations), 2),
                "avg_ms": round(sum(durations) / len(durations), 2),
                "min_ms": round(min(durations), 2),
                "max_ms": round(max(durations), 2),
                "fixture_count": len(durations),
            }

    # Build model list with parsed provider + base model + reasoning level
    model_list = []
    for m in sorted(models_set):
        model_name = model_data[m].get("_model", m)
        output_mode = model_data[m].get("_output_mode", "text")
        provider, base, rl = _parse_model_parts(model_name)
        model_list.append({
            "name": m,
            "provider": provider,
            "baseModel": base,
            "reasoningLevel": rl,
            "output_mode": output_mode,
        })

    # Build base_model_groups: group by (provider, baseModel)
    groups: dict[tuple[str, str], list[str]] = {}
    for m_data in model_list:
        key = (m_data["provider"], m_data["baseModel"])
        if key not in groups:
            groups[key] = []
        groups[key].append(m_data["name"])

    base_model_groups = []
    for (provider, base), model_names in groups.items():
        levels = []
        for mn in sorted(model_names):
            _, _, level = _parse_model_parts(mn)
            # Strip __json_schema suffix from level (it comes from the composite key)
            if level and level.endswith("__json_schema"):
                level = level[: -len("__json_schema")]
            ms = model_summaries.get(mn, {})
            levels.append({
                "level": level,
                "modelName": mn,
                "pass_at_k": ms.get("pass_at_k", 0),
                "total_cost_usd": ms.get("total_cost_usd"),
            })
        levels.sort(key=lambda l: (l["level"] or ""))
        base_model_groups.append({
            "provider": provider,
            "baseModel": base,
            "levels": levels,
        })

    runs_meta = []
    for run in runs:
        model_name = run.get("model", "")
        _, rl = parse_model_name(model_name)
        runs_meta.append({
            "timestamp": run.get("timestamp", ""),
            "model": run.get("model", ""),
            "profile": run.get("profile", ""),
            "git_sha": run.get("git_sha", ""),
            "benchmark_suite_version": run.get("benchmark_suite_version", ""),
            "reasoning_level": rl or "",
            "output_mode": run.get("output_mode", "text"),
        })

    # Build fixture index: "benchmark/fixture_id" → metadata
    # Fixture IDs are only unique within their benchmark
    fixture_index: dict[str, dict] = {}
    for run in runs:
        for result in run.get("results", []):
            bench = result.get("benchmark", "")
            for score in result.get("scores", []):
                fid = score.get("fixture_id", "")
                key = f"{bench}/{fid}"
                if fid and key not in fixture_index:
                    fixture_index[key] = {
                        "id": fid,
                        "benchmark": bench,
                        "prompt": score.get("prompt") or "",
                        "expected": score.get("expected") or "",
                        "description": score.get("description") or "",
                        "setup": score.get("setup") or [],
                        "purpose": score.get("purpose") or "",
                        "difficulty": score.get("difficulty") or "",
                        "tags": score.get("tags") or [],
                    }

    # Fall back: load any missing fixture metadata from YAML files
    _supplement_fixture_index_from_yaml(fixture_index)

    # Filter out the "unknown" model from all collections
    model_summaries.pop("unknown", None)
    model_runtimes.pop("unknown", None)
    matrix.pop("unknown", None)
    fixtures.pop("unknown", None)
    model_list = [m for m in model_list if m["name"] != "unknown"]
    runs_meta = [r for r in runs_meta if r["model"] != "unknown"]
    base_model_groups = [
        group
        for group in base_model_groups
        if group["provider"] != "unknown"
        and group["baseModel"] != "unknown"
        and all(level["modelName"] != "unknown" for level in group["levels"])
    ]

    return {
        "models": model_list,
        "benchmarks": sorted(benchmarks_set),
        "model_summaries": model_summaries,
        "model_runtimes": model_runtimes,
        "matrix": matrix,
        "fixtures": fixtures,
        "fixture_index": fixture_index,
        "runs_meta": runs_meta,
        "base_model_groups": base_model_groups,
    }


def render_json(data: dict[str, Any], output_path: str) -> None:
    """Write aggregated data as JSON for the Astro UI.

    Args:
        data: Aggregated data from aggregate_runs().
        output_path: Path to write the JSON file to.
    """
    import json as _json

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    serialized = _json.dumps(data, indent=2, default=str, allow_nan=False)
    path.write_text(serialized)


def write_sqlite_report_db(
    data: dict[str, Any],
    output_path: str | Path = REPORT_DB_PATH,
    schema_path: str | Path = REPORT_SCHEMA_PATH,
) -> None:
    """Legacy helper for SQLite parity tests.

    Production report publication writes compatibility JSON. The supported
    SQLite derivation path is ``web/scripts/build-db.mjs``.
    """
    db_path = Path(output_path)
    db_path.parent.mkdir(parents=True, exist_ok=True)
    if db_path.exists():
        db_path.unlink()

    schema = Path(schema_path).read_text()
    with sqlite3.connect(db_path) as conn:
        conn.execute("PRAGMA foreign_keys = ON")
        conn.executescript(schema)
        _insert_report_data(conn, data)
        conn.execute("ANALYZE")


def _json_dumps(value: Any) -> str:
    return json.dumps(
        value if value is not None else [],
        separators=(",", ":"),
        allow_nan=False,
    )


def _clean_model_name(name: str) -> tuple[str, str]:
    """Split a model name that may have a ``__json_schema`` composite suffix.

    ``aggregate_runs()`` produces composite keys such as
    ``openai/gpt-5:high__json_schema`` for JSON-schema results.  The SQLite
    schema stores *output_mode* in a dedicated column so the composite suffix
    must be stripped before insertion to avoid a double suffix when
    ``NodeSqliteReportStore`` reapplies it via :func:`modelModeKey`.

    Returns:
        ``(clean_name, output_mode)``.
    """
    suffix = "__json_schema"
    if name.endswith(suffix):
        return name[: -len(suffix)], "json_schema"
    return name, "text"


def _insert_report_data(conn: sqlite3.Connection, data: dict[str, Any]) -> None:
    models = data.get("models", [])
    benchmarks = data.get("benchmarks", [])

    conn.executemany(
        """
        INSERT INTO models (name, provider, base_model, reasoning_level, output_mode)
        VALUES (:name, :provider, :baseModel, :reasoningLevel, :output_mode)
        """,
        [
            {
                "name": _clean_model_name(m["name"])[0],
                "provider": m["provider"],
                "baseModel": m["baseModel"],
                "reasoningLevel": m["reasoningLevel"],
                "output_mode": _clean_model_name(m["name"])[1],
            }
            for m in models
        ],
    )
    conn.executemany(
        "INSERT INTO benchmarks (name) VALUES (?)",
        [(name,) for name in benchmarks],
    )

    # Build model_name → (clean_name, output_mode) lookup from model list
    model_mode_map: dict[str, tuple[str, str]] = {}
    for m in data.get("models", []):
        model_mode_map[m["name"]] = _clean_model_name(m["name"])

    conn.executemany(
        """
        INSERT INTO model_summaries (
          model_name, output_mode, total_runs, total_fixtures, total_passed, pass_at_k,
          total_cost_usd, avg_cost_usd
        )
        VALUES (
          :model_name, :output_mode, :total_runs, :total_fixtures, :total_passed, :pass_at_k,
          :total_cost_usd, :avg_cost_usd
        )
        """,
        [
            {
                "model_name": _clean_model_name(model_name)[0],
                "output_mode": _clean_model_name(model_name)[1],
                **summary,
            }
            for model_name, summary in data.get("model_summaries", {}).items()
        ],
    )

    conn.executemany(
        """
        INSERT INTO model_runtimes (
          model_name, output_mode, total_ms, avg_ms, min_ms, max_ms, fixture_count
        )
        VALUES (:model_name, :output_mode, :total_ms, :avg_ms, :min_ms, :max_ms, :fixture_count)
        """,
        [
            {
                "model_name": _clean_model_name(model_name)[0],
                "output_mode": _clean_model_name(model_name)[1],
                **runtime,
            }
            for model_name, runtime in data.get("model_runtimes", {}).items()
        ],
    )

    conn.executemany(
        """
        INSERT INTO benchmark_summaries (
          model_name, output_mode, benchmark_name, pass_at_k, total, passed, avg_similarity
        )
        VALUES (
          :model_name, :output_mode, :benchmark_name, :pass_at_k, :total, :passed, :avg_similarity
        )
        """,
        [
            {
                "model_name": _clean_model_name(model_name)[0],
                "output_mode": _clean_model_name(model_name)[1],
                "benchmark_name": benchmark,
                **cell,
            }
            for model_name, by_benchmark in data.get("matrix", {}).items()
            for benchmark, cell in by_benchmark.items()
        ],
    )

    fixture_rows = []
    tag_rows = []
    for fixture in data.get("fixture_index", {}).values():
        benchmark = fixture.get("benchmark", "")
        fixture_id = fixture.get("id", "")
        fixture_rows.append(
            {
                "benchmark_name": benchmark,
                "fixture_id": fixture_id,
                "prompt": fixture.get("prompt") or "",
                "expected": fixture.get("expected") or "",
                "description": fixture.get("description") or "",
                "setup_json": _json_dumps(fixture.get("setup")),
                "purpose": fixture.get("purpose") or "",
                "difficulty": fixture.get("difficulty") or "",
            }
        )
        for tag in fixture.get("tags") or []:
            tag_rows.append((benchmark, fixture_id, tag))

    conn.executemany(
        """
        INSERT INTO fixtures (
          benchmark_name, fixture_id, prompt, expected, description, setup_json,
          purpose, difficulty
        )
        VALUES (
          :benchmark_name, :fixture_id, :prompt, :expected, :description,
          :setup_json, :purpose, :difficulty
        )
        """,
        fixture_rows,
    )
    conn.executemany(
        """
        INSERT INTO fixture_tags (benchmark_name, fixture_id, tag)
        VALUES (?, ?, ?)
        """,
        tag_rows,
    )

    result_rows = []
    for model_name, by_benchmark in data.get("fixtures", {}).items():
        clean_name, clean_mode = _clean_model_name(model_name)
        for benchmark, fixtures_list in by_benchmark.items():
            for result in fixtures_list:
                # Serialize structured payloads as JSON strings
                parsed_payload = None
                if (
                    not result.get("structured_error")
                    and result.get("parsed_payload") is not None
                ):
                    parsed_payload = json.dumps(
                        result["parsed_payload"],
                        allow_nan=False,
                    )
                result_rows.append(
                    {
                        "model_name": clean_name,
                        "output_mode": result.get("output_mode", clean_mode),
                        "benchmark_name": benchmark,
                        "fixture_id": result.get("fixture_id", ""),
                        "passed": 1 if result.get("passed") else 0,
                        "similarity": result.get("similarity") or 0,
                        "error": result.get("error"),
                        "model_output": result.get("model_output") or "",
                        "reasoning_level": result.get("reasoning_level"),
                        "input_tokens": result.get("input_tokens"),
                        "output_tokens": result.get("output_tokens"),
                        "total_tokens": result.get("total_tokens"),
                        "reasoning_tokens": result.get("reasoning_tokens"),
                        "cost_usd": result.get("cost_usd"),
                        "duration_ms": result.get("duration_ms"),
                        "api_duration_ms": result.get("api_duration_ms"),
                        "purpose": result.get("purpose"),
                        "difficulty": result.get("difficulty"),
                        "tags_json": _json_dumps(result.get("tags")),
                        "parsed_payload": parsed_payload,
                        "raw_structured_output": result.get("raw_structured_output"),
                        "structured_error": result.get("structured_error"),
                    }
                )

    conn.executemany(
        """
        INSERT INTO fixture_results (
          model_name, output_mode, benchmark_name, fixture_id, passed, similarity, error,
          model_output, reasoning_level, input_tokens, output_tokens, total_tokens,
          reasoning_tokens, cost_usd, duration_ms, api_duration_ms, purpose, difficulty, tags_json,
          parsed_payload, raw_structured_output, structured_error
        )
        VALUES (
          :model_name, :output_mode, :benchmark_name, :fixture_id, :passed, :similarity, :error,
          :model_output, :reasoning_level, :input_tokens, :output_tokens,
          :total_tokens, :reasoning_tokens, :cost_usd, :duration_ms, :api_duration_ms, :purpose,
          :difficulty, :tags_json, :parsed_payload, :raw_structured_output, :structured_error
        )
        """,
        result_rows,
    )

    conn.executemany(
        """
        INSERT INTO runs (
          timestamp, model_name, output_mode, profile, git_sha, benchmark_suite_version,
          reasoning_level
        )
        VALUES (
          :timestamp, :model_name, :output_mode, :profile, :git_sha, :benchmark_suite_version,
          :reasoning_level
        )
        """,
        [
            {
                "timestamp": r.get("timestamp", ""),
                "model_name": _clean_model_name(r.get("model", ""))[0],
                "output_mode": r.get("output_mode", _clean_model_name(r.get("model", ""))[1]),
                "profile": r.get("profile", ""),
                "git_sha": r.get("git_sha", ""),
                "benchmark_suite_version": r.get("benchmark_suite_version", ""),
                "reasoning_level": r.get("reasoning_level", ""),
            }
            for r in data.get("runs_meta", [])
        ],
    )

    for group in data.get("base_model_groups", []):
        cursor = conn.execute(
            """
            INSERT INTO base_model_groups (provider, base_model)
            VALUES (?, ?)
            """,
            (group.get("provider", ""), group.get("baseModel", "")),
        )
        group_id = cursor.lastrowid
        conn.executemany(
            """
            INSERT INTO base_model_group_levels (
              group_id, level, model_name, output_mode, pass_at_k, total_cost_usd
            )
            VALUES (?, ?, ?, ?, ?, ?)
            """,
            [
                (
                    group_id,
                    (level.get("level") or "").replace("__json_schema", "") or None,
                    _clean_model_name(level.get("modelName", ""))[0],
                    _clean_model_name(level.get("modelName", ""))[1],
                    level.get("pass_at_k", 0),
                    level.get("total_cost_usd"),
                )
                for level in group.get("levels", [])
            ],
        )

    _insert_campaign_data(conn, data)


def _insert_campaign_data(
    conn: sqlite3.Connection, data: dict[str, Any]
) -> None:
    """Insert campaign-aware report data when present in the aggregate.

    The legacy single-result schema does not include ``campaigns``, so this
    function is a no-op for historical artifacts.
    """
    campaigns = data.get("campaigns", [])
    if not campaigns:
        return

    for campaign in campaigns:
        _insert_single_campaign(conn, campaign)


def _insert_single_campaign(
    conn: sqlite3.Connection, campaign: dict[str, Any]
) -> None:
    """Insert one campaign and all of its derived rows."""
    campaign_id = campaign.get("campaign_id", "")
    conn.execute(
        """
        INSERT INTO campaigns (
          campaign_id, created_at, config_hash, state,
          planned_attempts, completed_attempts, valid_attempts,
          passing_attempts, excluded_attempts, publication_state,
          legacy, benchmark_ids_json, model_ids_json, output_modes_json,
          planned_trial_count
        )
        VALUES (
          :campaign_id, :created_at, :config_hash, :state,
          :planned_attempts, :completed_attempts, :valid_attempts,
          :passing_attempts, :excluded_attempts, :publication_state,
          :legacy, :benchmark_ids_json, :model_ids_json, :output_modes_json,
          :planned_trial_count
        )
        """,
        {
            "campaign_id": campaign_id,
            "created_at": campaign.get("created_at", ""),
            "config_hash": campaign.get("config_hash", ""),
            "state": campaign.get("state", "incomplete"),
            "planned_attempts": campaign.get("planned_attempts", 0),
            "completed_attempts": campaign.get("completed_attempts", 0),
            "valid_attempts": campaign.get("valid_attempts", 0),
            "passing_attempts": campaign.get("passing_attempts", 0),
            "excluded_attempts": campaign.get("excluded_attempts", 0),
            "publication_state": campaign.get("publication_state", "draft"),
            "legacy": 1 if campaign.get("legacy") else 0,
            "benchmark_ids_json": _json_dumps(campaign.get("benchmark_ids", [])),
            "model_ids_json": _json_dumps(campaign.get("model_ids", [])),
            "output_modes_json": _json_dumps(campaign.get("output_modes", [])),
            "planned_trial_count": campaign.get("planned_trial_count", 1),
        },
    )

    for trial in campaign.get("trials", []):
        conn.execute(
            """
            INSERT INTO trials (
              campaign_id, trial_index, planned_attempts,
              completed_attempts, valid_attempts, passing_attempts,
              excluded_attempts, complete
            )
            VALUES (
              :campaign_id, :trial_index, :planned_attempts,
              :completed_attempts, :valid_attempts, :passing_attempts,
              :excluded_attempts, :complete
            )
            """,
            {
                "campaign_id": campaign_id,
                "trial_index": trial.get("trial_index", 0),
                "planned_attempts": trial.get("planned_attempts", 0),
                "completed_attempts": trial.get("completed_attempts", 0),
                "valid_attempts": trial.get("valid_attempts", 0),
                "passing_attempts": trial.get("passing_attempts", 0),
                "excluded_attempts": trial.get("excluded_attempts", 0),
                "complete": 1 if trial.get("complete") else 0,
            },
        )

    for attempt in campaign.get("raw_attempts", []):
        identity = attempt.get("identity", {})
        fixture_id = identity.get("fixture_id", "")
        benchmark_name = identity.get("benchmark") or (
            fixture_id.split("/")[0] if "/" in fixture_id else ""
        )
        conn.execute(
            """
            INSERT INTO raw_attempts (
              campaign_id, trial_index, model_name, reasoning_level,
              output_mode, benchmark_name, fixture_id, status, passed,
              similarity, error, model_output, input_tokens, output_tokens,
              total_tokens, reasoning_tokens, cost_usd, api_duration_ms,
              request_telemetry_json, provider_route_metadata_json,
              judge_evidence_json, safety_state, safety_cost_usd,
              provenance_json
            )
            VALUES (
              :campaign_id, :trial_index, :model_name, :reasoning_level,
              :output_mode, :benchmark_name, :fixture_id, :status, :passed,
              :similarity, :error, :model_output, :input_tokens, :output_tokens,
              :total_tokens, :reasoning_tokens, :cost_usd, :api_duration_ms,
              :request_telemetry_json, :provider_route_metadata_json,
              :judge_evidence_json, :safety_state, :safety_cost_usd,
              :provenance_json
            )
            """,
            {
                "campaign_id": campaign_id,
                "trial_index": identity.get("trial_index", 0),
                "model_name": identity.get("model_id", ""),
                "reasoning_level": identity.get("reasoning_effort"),
                "output_mode": identity.get("output_mode", "text"),
                "benchmark_name": benchmark_name,
                "fixture_id": fixture_id,
                "status": attempt.get("status", "pending"),
                "passed": 1 if attempt.get("passed") else 0,
                "similarity": attempt.get("similarity"),
                "error": attempt.get("error"),
                "model_output": attempt.get("model_output", ""),
                "input_tokens": attempt.get("input_tokens"),
                "output_tokens": attempt.get("output_tokens"),
                "total_tokens": attempt.get("total_tokens"),
                "reasoning_tokens": attempt.get("reasoning_tokens"),
                "cost_usd": attempt.get("cost_usd"),
                "api_duration_ms": attempt.get("api_duration_ms"),
                "request_telemetry_json": _json_dumps(
                    attempt.get("request_telemetry")
                ),
                "provider_route_metadata_json": _json_dumps(
                    attempt.get("provider_route_metadata")
                ),
                "judge_evidence_json": _json_dumps(attempt.get("judge_evidence")),
                "safety_state": attempt.get("safety_state"),
                "safety_cost_usd": attempt.get("safety_cost_usd"),
                "provenance_json": _json_dumps(attempt.get("provenance")),
            },
        )

    for aggregate in campaign.get("fixture_aggregates", []):
        fixture_id = aggregate.get("fixture_id", "")
        benchmark_name = aggregate.get("benchmark") or (
            fixture_id.split("/")[0] if "/" in fixture_id else ""
        )
        conn.execute(
            """
            INSERT INTO fixture_aggregates (
              campaign_id, benchmark_name, fixture_id, model_name,
              reasoning_level, output_mode, planned_trials,
              completed_trials, valid_attempts, passing_attempts,
              failing_attempts, excluded_attempts, mean_success_rate,
              pass_any_at_n_json, reliability_classification, incomplete
            )
            VALUES (
              :campaign_id, :benchmark_name, :fixture_id, :model_name,
              :reasoning_level, :output_mode, :planned_trials,
              :completed_trials, :valid_attempts, :passing_attempts,
              :failing_attempts, :excluded_attempts, :mean_success_rate,
              :pass_any_at_n_json, :reliability_classification, :incomplete
            )
            """,
            {
                "campaign_id": campaign_id,
                "benchmark_name": aggregate.get("benchmark") or benchmark_name,
                "fixture_id": fixture_id,
                "model_name": aggregate.get("model_id") or "",
                "reasoning_level": aggregate.get("reasoning_effort") or "",
                "output_mode": aggregate.get("output_mode") or "text",
                "planned_trials": aggregate.get("planned_trials", 0),
                "completed_trials": aggregate.get("completed_trials", 0),
                "valid_attempts": aggregate.get("valid_attempts", 0),
                "passing_attempts": aggregate.get("passing_attempts", 0),
                "failing_attempts": aggregate.get("failing_attempts", 0),
                "excluded_attempts": aggregate.get("excluded_attempts", 0),
                "mean_success_rate": aggregate.get("mean_success_rate"),
                "pass_any_at_n_json": _json_dumps(aggregate.get("pass_any_at_n", {})),
                "reliability_classification": aggregate.get(
                    "reliability_classification"
                ),
                "incomplete": 1 if aggregate.get("incomplete") else 0,
            },
        )

    for summary in campaign.get("model_summaries", []):
        conn.execute(
            """
            INSERT INTO campaign_model_summaries (
              campaign_id, model_name, reasoning_level, output_mode, planned_trials,
              completed_trials, valid_attempts, passing_attempts,
              excluded_attempts, mean_success_rate, pass_any_at_n_json,
              incomplete, resource_summary_json
            )
            VALUES (
              :campaign_id, :model_name, :reasoning_level, :output_mode, :planned_trials,
              :completed_trials, :valid_attempts, :passing_attempts,
              :excluded_attempts, :mean_success_rate, :pass_any_at_n_json,
              :incomplete, :resource_summary_json
            )
            """,
            {
                "campaign_id": campaign_id,
                "model_name": summary.get("model_id", ""),
                "reasoning_level": summary.get("reasoning_effort") or "",
                "output_mode": summary.get("output_mode") or "text",
                "planned_trials": summary.get("planned_trials", 0),
                "completed_trials": summary.get("completed_trials", 0),
                "valid_attempts": summary.get("valid_attempts", 0),
                "passing_attempts": summary.get("passing_attempts", 0),
                "excluded_attempts": summary.get("excluded_attempts", 0),
                "mean_success_rate": summary.get("mean_success_rate"),
                "pass_any_at_n_json": _json_dumps(summary.get("pass_any_at_n", {})),
                "incomplete": 1 if summary.get("incomplete") else 0,
                "resource_summary_json": _json_dumps(
                    summary.get("resource_summary")
                ),
            },
        )

    for summary in campaign.get("benchmark_summaries", []):
        conn.execute(
            """
            INSERT INTO campaign_benchmark_summaries (
              campaign_id, benchmark_name, planned_trials,
              completed_trials, valid_attempts, passing_attempts,
              excluded_attempts, mean_success_rate, pass_any_at_n_json,
              incomplete, resource_summary_json
            )
            VALUES (
              :campaign_id, :benchmark_name, :planned_trials,
              :completed_trials, :valid_attempts, :passing_attempts,
              :excluded_attempts, :mean_success_rate, :pass_any_at_n_json,
              :incomplete, :resource_summary_json
            )
            """,
            {
                "campaign_id": campaign_id,
                "benchmark_name": summary.get("benchmark", ""),
                "planned_trials": summary.get("planned_trials", 0),
                "completed_trials": summary.get("completed_trials", 0),
                "valid_attempts": summary.get("valid_attempts", 0),
                "passing_attempts": summary.get("passing_attempts", 0),
                "excluded_attempts": summary.get("excluded_attempts", 0),
                "mean_success_rate": summary.get("mean_success_rate"),
                "pass_any_at_n_json": _json_dumps(summary.get("pass_any_at_n", {})),
                "incomplete": 1 if summary.get("incomplete") else 0,
                "resource_summary_json": _json_dumps(
                    summary.get("resource_summary")
                ),
            },
        )

    for idx, summary in enumerate(campaign.get("resource_summaries", [])):
        conn.execute(
            """
            INSERT INTO resource_summaries (
              id, campaign_id, scope, total_cost_usd, total_input_tokens,
              total_output_tokens, total_tokens, total_reasoning_tokens,
              total_api_duration_ms, total_wall_duration_ms,
              mean_cost_per_complete_trial_usd, mean_tokens_per_complete_trial,
              mean_api_duration_per_complete_trial_ms, partial_pricing
            )
            VALUES (
              :id, :campaign_id, :scope, :total_cost_usd, :total_input_tokens,
              :total_output_tokens, :total_tokens, :total_reasoning_tokens,
              :total_api_duration_ms, :total_wall_duration_ms,
              :mean_cost_per_complete_trial_usd, :mean_tokens_per_complete_trial,
              :mean_api_duration_per_complete_trial_ms, :partial_pricing
            )
            """,
            {
                "id": idx + 1,
                "campaign_id": campaign_id,
                "scope": summary.get("scope", "campaign"),
                "total_cost_usd": summary.get("total_cost_usd"),
                "total_input_tokens": summary.get("total_input_tokens"),
                "total_output_tokens": summary.get("total_output_tokens"),
                "total_tokens": summary.get("total_tokens"),
                "total_reasoning_tokens": summary.get("total_reasoning_tokens"),
                "total_api_duration_ms": summary.get("total_api_duration_ms"),
                "total_wall_duration_ms": summary.get("total_wall_duration_ms"),
                "mean_cost_per_complete_trial_usd": summary.get(
                    "mean_cost_per_complete_trial_usd"
                ),
                "mean_tokens_per_complete_trial": summary.get(
                    "mean_tokens_per_complete_trial"
                ),
                "mean_api_duration_per_complete_trial_ms": summary.get(
                    "mean_api_duration_per_complete_trial_ms"
                ),
                "partial_pricing": 1 if summary.get("partial_pricing") else 0,
            },
        )

    safety_summary = campaign.get("safety_summary") or {}
    conn.execute(
        """
        INSERT INTO publication_states (
          campaign_id, reviewed_count, sanitized_count,
          blocked_count, pending_count
        )
        VALUES (:campaign_id, :reviewed_count, :sanitized_count, :blocked_count, :pending_count)
        """,
        {
            "campaign_id": campaign_id,
            "reviewed_count": safety_summary.get("reviewed", 0),
            "sanitized_count": safety_summary.get("sanitized", 0),
            "blocked_count": safety_summary.get("blocked", 0),
            "pending_count": safety_summary.get("pending", 0),
        },
    )


def _supplement_fixture_index_from_yaml(fixture_index: dict[str, dict]) -> None:
    """Fill in missing fixture metadata by loading YAML fixture files.

    Only fills fields that are missing in the index.
    """
    fixtures_dir = Path(__file__).parent.parent / "fixtures"
    if not fixtures_dir.exists():
        return

    for key, entry in fixture_index.items():
        fid = entry.get("id", "")
        bench = entry.get("benchmark", "")
        if not fid or not bench:
            continue

        needs_yaml = (
            not entry.get("prompt")
            or not entry.get("expected")
            or not entry.get("description")
            or not entry.get("setup")
            or not entry.get("purpose")
            or not entry.get("difficulty")
            or not entry.get("tags")
        )
        if not needs_yaml:
            continue

        # Try to find the fixture YAML file
        yaml_path = fixtures_dir / bench / f"{fid}.yaml"
        if not yaml_path.exists():
            continue

        try:
            import yaml
            data = yaml.safe_load(yaml_path.read_text())
            if isinstance(data, dict):
                entry["prompt"] = entry.get("prompt") or data.get("prompt", "")
                entry["expected"] = entry.get("expected") or data.get("expected", "")
                entry["description"] = entry.get("description") or data.get("description", "")
                entry["setup"] = entry.get("setup") or data.get("setup", [])
                entry["purpose"] = entry["purpose"] or data.get("purpose", "")
                entry["difficulty"] = entry["difficulty"] or data.get("difficulty", "")
                entry["tags"] = entry["tags"] or data.get("tags", [])
        except Exception as exc:
            logger.debug("Failed to load YAML for fixture %s: %s", fid, exc)
